routes/web.php
<?php

Auth::routes();

Route::get('/', 'MessageController@index')->name('home');
Route::post('/message', 'MessageController@store')->name('message.store');
Route::delete('/message/{message}', 'MessageController@destroy')->name('message.destroy');
Route::post('/message/{message}/comment', 'CommentController@store')->name('comment.store');
Route::delete('/message/{message}/comment/{comment}', 'CommentController@destroy')->name('comment.destroy');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['body'];

    protected $touches = ['message'];

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function message()
    {
        return $this->belongsTo(Message::class);
    }
}

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $fillable = [];

    public function comments() {
        return $this->hasMany(Comment::class);
    }

    public function sender() {
        return $this->belongsTo(User::class, 'sender_id');
    }

    public function recipient() {
        return $this->belongsTo(User::class, 'recipient_id');
    }

    public function getQuestionAttribute()
    {
        return $this->comments->first();
    }

    public function getAnswerAttribute()
    {
        if ($this->comments->count() < 2) {
            return null;
        }
        return $this->comments->last();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'full_name', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function availableMessages()
    {
        $query = Message::query()->latest();
        // ->orderBy('updated_at', 'desc')
        if ($this->role === 'jury') {
            return $query;
        }

        $query->where('sender_id', $this->id)
            ->orWhere(function ($query) {
                $query->where('type', 'message')->where(function ($query) {
                    $query->where('recipient_id', 0)->orWhere('recipient_id', $this->id);
                });
            });
        return $query;
    }

    public function getDisplayNameAttribute()
    {
        if (Auth::user()->role === 'participant' && $this->role === 'jury') {
            return 'Жюри';
        }
        return $this->full_name;
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use App\Models\Message;
use Illuminate\Http\Request;
use Auth;
use Session;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'role:jury']);
    }

    public function store(Message $message, CommentRequest $request)
    {
        if ($message->comments()->count() > 1) {
            Session::flash('status', 'Кто-то уже ответил на этот вопрос!');
            return back();
        }

        $comment = new Comment(['body' => $request->body]);
        $comment->message()->associate($message);
        $comment->author()->associate(Auth::user()->id);
        $comment->save();
        $comment->message->touch();
        Session::flash('status', 'Ответ на вопрос успешно добавлен!');
        return redirect()->route('home');
    }

    public function destroy(Message $message, Comment $comment)
    {
        $comment->delete();
        Session::flash('status', 'Ответ успешно удален');
        return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use App\Models\Message;
use App\Models\User;
use Illuminate\Http\Request;
use Auth;
use Session;

class MessageController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:jury')->only('destroy');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $messages = Auth::user()->availableMessages()->with('comments', 'comments.author')->get();
        $unansweredMessages = Auth::user()->availableMessages()->has('comments', '<=', 1)
            ->where('type', 'question')->count();
        return view('home')->with(compact('users', 'messages', 'unansweredMessages'));
    }

    /**
     *
     * @param CommentRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request)
    {
        $comment = new Comment(['body' => $request->body]);
        $comment->author()->associate(Auth::user()->id);

        $message = new Message();
        $message->sender()->associate(Auth::user()->id);
        $message->recipient_id = 0;
        if (Auth::user()->role === 'jury') {
            $message->type = 'message';
            $message->recipient_id = $request->recipient_id;
        }
        $message->save();

        $comment->message()->associate($message);
        $comment->save();
        Session::flash('status', 'Отправлено успешно!');
        return redirect()->route('home');
    }

    public function destroy(Message $message)
    {
        $message->delete();
        Session::flash('status', 'Сообщение/Вопрос успешно удалено');
        return back();
    }
}

resources/views/comments/view.blade.php
<div class="media">
    @isset ($title)
        <div class="media-left">
            {{$title}}
        </div>
    @endisset
    <div class="media-body">
        <h5 class="media-heading">
            <span>
                <strong>{{ $comment->author->display_name }}</strong>
            </span>
            <br>
            <small>
                {{ $comment->created_at->format('d.m.Y H:i:s') }}
                @isset ($delete)
                @if ($delete && Auth::user()->role === 'jury')
                    <a href="{{route('comment.destroy', ['message' => $comment->message->id, 'comment' => $comment->id])}}"
                       data-method="delete"
                       data-confirm="Вы уверены что хотите удалить ответ на вопрос #{{ $comment->message->id }}?"
                    >
                        Удалить ответ
                    </a>
                @endif
                @endisset
            </small>
        </h5>
        <p>{{ $comment->body }}</p>
        {{ $slot }}
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @if(Auth::user()->role === 'jury' && $unansweredMessages > 0)
                <div class="alert alert-danger" role="alert">
                    Внимание! Количество вопросов без ответа: {{ $unansweredMessages }}
                </div>
            @endif

            @if(Auth::user()->role === 'participant')
                @include('questions/create')
            @endif

            @if(Auth::user()->role === 'jury')
                @include('messages/create')
            @endif

            @forelse($messages as $message)
                @if($message->type === 'message')
                    @include('messages/view', compact($message))
                @elseif($message->type === 'question')
                    @include('questions/view', compact($message))
                @endif
            @empty
                <div class="panel panel-default">
                    <div class="panel-heading">Чат с жюри</div>
                    <div class="panel-body">
                        <p>В системе пока еще нет сообщений</p>
                    </div>
                </div>
            @endforelse
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    {{--<meta http-equiv="refresh" content="30">--}}
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Войти</a></li>
                            {{--<li><a href="{{ route('register') }}">Register</a></li>--}}
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->full_name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Выйти
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')

        <div class="text-center">
            &copy; {{ date('Y') }} {{ config('app.name') }}. &beta;-версия
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/laravel.js') }}"></script>
</body>
</html>

resources/views/messages/create.blade.php
<div class="panel panel-default">
    <div class="panel-heading">Отправить сообщение</div>

    <div class="panel-body">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <form class="form-horizontal" method="POST" action="{{ route('message.store') }}">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('recipient_id') ? ' has-error' : '' }}">
                <label for="recipient" class="col-md-3 control-label">Получатель</label>

                <div class="col-md-9">
                    <select class="form-control" name="recipient_id" id="recipient">
                        <option value="0">Все участники</option>
                        @foreach($users as $user)
                            <option value="{{ $user->id }}">{{ $user->full_name }}</option>
                        @endforeach
                    </select>

                    @if ($errors->has('recipient_id'))
                        <span class="help-block">
                            <strong>{{ $errors->first('recipient_id') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                <label for="body" class="col-md-3 control-label">Сообщение</label>

                <div class="col-md-9">
                    <textarea class="form-control" name="body" id="body"></textarea>

                    @if ($errors->has('body'))
                        <span class="help-block">
                            <strong>{{ $errors->first('body') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">
                        Отправить сообщение
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/messages/view.blade.php
<div class="panel panel-info">
    <div class="panel-heading">
        <span>
            {{ $message->recipient_id === 0 ? 'Сообщение' : 'Персональное сообщение' }}
            #{{ $message->id }}
            @if (Auth::user()->role === 'jury')
                <a href="{{route('message.destroy', ['message' => $message->id])}}"
                   data-method="delete"
                   data-confirm="Вы уверены что хотите удалить сообщение #{{ $message->id }}?"
                >
                    Удалить
                </a>
            @endif
        </span>
        <span class="pull-right text-muted">{{ $message->created_at->format('d.m.Y H:i:s') }}</span>
    </div>

    <div class="panel-body">
        @if (Auth::user()->role === 'jury')
            <p><strong>Получатель:</strong> {{ $message->recipient->display_name ??  'Все участники' }}</p>
        @endif
        @forelse ($message->comments as $comment)
            @component('comments.view', ['comment' => $comment])
            @endcomponent
        @empty
            <p>Что-то не так с системой чат жюри!</p>
        @endforelse
    </div>
</div>

resources/views/questions/create.blade.php
<div class="panel panel-default">
    <div class="panel-heading">Задать вопрос</div>

    <div class="panel-body">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <p>
            Старайтесь сформулировать вопрос так, чтобы жюри могло дать ответ «да» или «нет». В противном случае Вы рискуете получить ответ «без комментариев».
        </p>

        <p>
            Если вопрос связан с технической неисправностью, не забудьте указать номер своего рабочего места.
        </p>

        <p>
            Если вопрос связан с задачей, не забудьте указать номер или название задачи.
        </p>
        <form class="form-horizontal" method="POST" action="{{ route('message.store') }}">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                <label for="body" class="col-md-2 control-label">Вопрос</label>

                <div class="col-md-10">
                    <textarea class="form-control" name="body" id="body"></textarea>

                    @if ($errors->has('body'))
                        <span class="help-block">
                            <strong>{{ $errors->first('body') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group">

                <div class="col-md-10 col-md-offset-2">
                    <button type="submit" class="btn btn-primary">
                        Задать вопрос
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/questions/view.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <span>Вопрос #{{ $message->id }}</span>
        <span class="pull-right text-muted">{{ $message->created_at->format('d.m.Y H:i:s') }}</span>
    </div>

    <div class="panel-body">
        @if ( $message->question )
            @component('comments.view', ['comment' => $message->question])
                @if ($message->answer)
                    @component('comments.view', ['comment' => $message->answer, 'delete' => true])
                        @slot('title')
                            <img src="/images/envelope.png" width="32" height="32" class="media-object">
                        @endslot
                    @endcomponent
                @elseif (Auth::user()->role === 'jury')
                    <div class="media">
                        <div class="media-left">
                            <img src="/images/envelope.png" width="32" height="32" class="media-object">
                        </div>
                        <div class="media-body">

                            <h5 class="media-heading">
                                <strong>Жюри</strong>
                            </h5>
                            <form class="form-horizontal" method="POST" action="{{ route('comment.store', ['message' => $message->id]) }}">
                                {{ csrf_field() }}

                                <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                                    <div class="col-md-12">
                                        <textarea class="form-control input-body" name="body"></textarea>
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                                    <div class="col-md-12">
                                        Быстрые ответы:
                                        <a href="javascript://"
                                           onclick="this.parentElement.parentElement.parentElement.querySelector('textarea.input-body').innerHTML = 'Да'
                                            "
                                        >Да</a>
                                        <a href="javascript://"
                                           onclick="this.parentElement.parentElement.parentElement.querySelector('textarea.input-body').innerHTML = 'Нет' "
                                        >Нет</a>
                                        <a href="javascript://"
                                           onclick="this.parentElement.parentElement.parentElement.querySelector('textarea.input-body').innerHTML = 'Без комментариев' "
                                        >Без комментариев</a>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-primary">
                                            Ответить
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                @else
                    <strong>Жюри пока еще не ответило на этот вопрос</strong>
                @endif

            @endcomponent
        @endif
    </div>
</div>